services:  
  mysql:  
    image: mysql  
    restart: always  
    environment:  
      MYSQL_ROOT_PASSWORD: 1234  
    ports:  
      - "3102:3306"  
    volumes:  
      - ./mysql_data:/var/lib/mysql

  admin:  
    image: phpmyadmin  
    restart: always   
    ports:  
      - "6700:80"  
    environment:  
      PMA_HOST: mysql   
  web:  
    image: nginx  
    ports:  
      - "8060:80" 
    volumes:  
      - ./:/var/www/html 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on:  
      - php  

  php:  
    image: php:8.2-fpm  
    volumes:  
      - ./:/var/www/html
    build:  
      context: .  
      dockerfile: Dockerfile